{% set name = "microbench" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alubbock/microbench/archive/v{{ version }}.tar.gz
  sha256: 66c742d71560b2354c5d11c127ca6ffbea8f6d3e3d75fbaaf6aac80369c99b46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.6
    - pip
    - setuptools
  run:
    - python >=2.6
    - setuptools

test:
  imports:
    - microbench
  commands:
    - pip check
    - ls
    - pytest microbench/tests/
  source_files:
    - .
  requires:
    - pip
    - pytest
    - pandas
    - line_profiler
    - psutil 

about:
  home: https://github.com/alubbock/microbench
  summary: Micro-benchmarking framework. Extensible, with distributed/cluster support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
